### ISSUE TITLE
create within db_utilities pandas to sql data type functions

### ISSUE THREAD

**Issue by jordan-carson** [Jordan-Matt/rice#11]
Create a function that will map pandas datatypes to sql data types, this can be extended in future pulls to other frameworks.

**Comment by matthewmturner** [comment]
so i understand the use case - would this be for creating a table in a DB so that you pass the correct dtypes?  which db first? postgres?

**Comment by jordan-carson** [comment]
good question so that will be an argument of the function, and it will map it based on the library like pyodbc, or psycopg2 - using the typing library, which has a MappingProxyType

**Comment by matthewmturner** [comment]
ok. i think we should start with only postgres/psycopg2  - i already have a db for us to use so itll be easy to test.  from there well do based on need (i.e we start using another db).

**Comment by jordan-carson** [comment]
ok how can we both connect to the db locally?

**Comment by jordan-carson** [comment]
dbeaver is great for postgresql

**Comment by matthewmturner** [comment]
i will message you credentials.

i usually use pgadmin4. But I have used dbeaver a lot and def like it.

**Comment by jordan-carson** [comment]
ok, for now, we can close this issue as the db_utilities satisfy what the issue was requiring for enhancements. We will add more functionality along the way.
