### ISSUE TITLE
Build db_utility functions for updating, executing, inserting and bulk_inserting data into sql databases.

### ISSUE THREAD

**Issue by jordan-carson** [Jordan-Matt/rice#13]
This will require multiple functions, but we want to have a function that will bulk insert data into a sql database that will be faster than pandas.DataFrame.to_sql(), which the user can specify the chunk size. Also, implement create_table, execute_sql functions for creating new objects and executing stored_procs.

**Comment by matthewmturner** [comment]
shall we use postgres as our first testing ground?

**Comment by jordan-carson** [comment]
Yes, agree we should use postgresql as our first test - the main reason for this issue is because to_sql is very slow, and I want to create a function that will upload chunks of a dataframe into a database much faster. We can use postgresql as our testing db.

**Comment by jordan-carson** [comment]
Duplicate issue - issue covered and closed.
