### ISSUE TITLE
create stat functions

### ISSUE THREAD

**Issue by jordan-carson** [Jordan-Matt/rice#40]
within a new folder, create stat functions to be used on pandas columns

**Comment by matthewmturner** [comment]
example functions?  why not have this within df_utils

**Comment by jordan-carson** [comment]
Do you think we should separate stat functions like calculating confidence intervals versus dataframe utilities functions such as calc_cardinality, or df_stats on a dataframe. Thoughts?

**Comment by jordan-carson** [comment]
Example Below:

`import pandas as pd
import numpy as np


def create_confidence_intervals(mean, tstar, std_error):
    lower_confidence_bound = mean - tstar * std_error
    upper_confidence_bound = mean + tstar * std_error
    return lower_confidence_bound, upper_confidence_bound


def confint_series(series: pd.Series, n: int, tstar: int):
    mean = series.mean()
    sd = series.std()
    std_error = sd / np.sqrt(n)
    return (mean - tstar * std_error), (mean + tstar * std_error)
`

**Comment by jordan-carson** [comment]
im going to close this - we should just be using functions already available to us in scipy i.e. 
```python
sm.stats.proportion_confint(1413, 1413+1340)  
```
