### ISSUE TITLE
the target library setup needs to be defined and implemented

### ISSUE THREAD

**Issue by matthewmturner** [Jordan-Matt/rice#5]
we need to think how we will use and import the library and then implement this.

for example we could do some of the following:

1. import rice as rc - 
2. from rice import utils/decorators etc.

whatever we choose then we need to setup the library appropriately.
then we should each install using pip install -e to use locally in editable mode.

**Comment by matthewmturner** [comment]
do we actually need src? based on our current setup i dont think its required.  i think if we wanted to use it it would have been in the main project space, then within that we would have rice.  but since we have rice at the main project level we can just get rid of src now and just have the files we want.

**Comment by jordan-carson** [comment]
no we don't need it, we just need to make sure that we have our __init__.py files created importing the appropriate functions, classes, objects and what not so when we import this library we can do rice.[obj] without needing rice.src.db_utilities.....

**Comment by matthewmturner** [comment]
this is where we need to consider design trade offs.

in case 1 we use the __init __.py file to pull in all the functions we want to expose but then we need to manage and update that file for all additions.  this is like pandas.

in case two it would be more like

from rice.db_utilities import db_access

what do you think?

either way i think we want to get rid of src

**Comment by jordan-carson** [comment]
I am fine with whatever approach you choose, in pycharm if you refactor any variable it will automatically be updated in the init file, but you will still need to push that file to master.

**Comment by matthewmturner** [comment]
but if we add a new file with new functions we'll have to decide which of those go in the __init__ space.  Were basically making design choices by deciding what goes in the init.

i think to start its simpler if we dont add scripts/functions to __init__.  As the project goes we can reevaluate that.

i think the only thing to do then is tak everything wihtin src and put it in rice directory directly now.

**Comment by jordan-carson** [comment]
ok lets remove the src folder and reorganize all folders under rice, we can exclude the init files for now.
