### ISSUE TITLE
synchronize docstring format

### ISSUE THREAD

**Issue by matthewmturner** [Jordan-Matt/rice#7]
need to agree upon docstring format and update existing code to reflect this.

**Comment by jordan-carson** [comment]
Yes, does vs code provide you with a template docstring when you create a docstring under a function call?

**Comment by matthewmturner** [comment]
its an extension i use.  i need to look into if i can customize it or if vs code lets me configure.  will look into it and come back to this.

**Comment by jordan-carson** [comment]
All docstrings should include a comment about what the function is doing, as well as the parameters of the function. For example, see below. If that extension allows this, then let's use it.
`    """
    Applies functions(s) to DataFrame.
    @param df: pandas.DataFrame
    @param funcs: callable function or dict containing column: list of callable functions.
    @return: resulting pandas.DataFrame
    """`

**Comment by matthewmturner** [comment]
Agree on all of those.  It was more for the actual style choices (for example i think pycharm uses @). How i generate in vs code looks diff.  This isnt a high priority one. We should each docstring as we go still and im going to look into if vs code gives me any flexibility with this.

**Comment by matthewmturner** [comment]
as discussed we will use numpy for docstrings.  lets use those going forward and we will migrate existing doc strings over time.  closing this.
